#!/bin/sh
### BEGIN INIT INFO
# Provides:	  {{server-name}}
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO
. /lib/init/vars.sh
. /lib/lsb/init-functions
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON={{python}}
DAEMON_OPTS="{{path-to-DDDProxy}}/{{entry-point}} -p {{port-setting}} {{auth}} --logFile /tmp/{{server-name}}.log"
start(){
	echo -n "Starting {{server-name}}: ";
	start-stop-daemon --start --background --make-pidfile --pidfile $PID --exec $DAEMON -- $DAEMON_OPTS 2>/dev/null\
		|| return 2
}
stop(){
	start-stop-daemon --stop --pidfile $PID
	RETVAL="$?"
	sleep 1
	return "$RETVAL"
}
case $1 in
start)
	start;
	case "$?" in
			0|1) log_end_msg 0 ;;
			2)   log_end_msg 1 ;;
	esac
	;;
stop)
	stop;
	case "$?" in
		0|1) log_end_msg 0 ;;
		2)   log_end_msg 1 ;;
	esac
	;;
restart)
	stop;
	case "$?" in
		0|1) log_end_msg 0 ;;
		2)   log_end_msg 1 ;;
	esac
	start;
	case "$?" in
		0|1) log_end_msg 0 ;;
		2)   log_end_msg 1 ;;
	esac
	;;
esac